# Generated by Django 3.1.5 on 2022-06-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220603_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avator',
            field=models.ImageField(default='avators/avator.png', upload_to='avators'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='backgrounds/background.jpg', upload_to='backgrounds'),
        ),
    ]
